version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
  web:
    build: .
    ports:
      - "8080:80"
    links:
      - "db"
    environment:
      APP_ENV: local
      APP_KEY: p1jb7h4dZMrBt6qpYnQCQYI06UZa5jRk
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mysql
      DB_USERNAME: root
      DB_PASSWORD: mysql
