version: '2'
services:
  db:
    image: runnable/mysql:5.6
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
